image: python:3.8

stages:
  - test

test:
  stage: test
  script:
    - apt-get update && apt-get install -y wget unzip
    - apt-get install -y chromium
    - pip install --upgrade pip  # Обновляем pip
    - pip install -r requirements.txt  # Устанавливаем зависимости
    - pip install webdriver-manager  # Устанавливаем webdriver-manager
    - pytest test.py  # Запускаем тесты
  variables:
    DISPLAY: ":99"
