stages:
  - test

test_job:
  stage: test
  image: python:3.8-slim  # Используем более легковесный образ
  services:
    - name: selenium/standalone-chrome  # Используем сервис Selenium с Chrome
      alias: selenium
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest test.py
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'  # Запускать только для ветки master
