stages:
  - test

test_job:
  stage: test
  image: python:3.8
  services:
    - name: selenium/standalone-chrome  # Используем сервис Selenium с Chrome
      alias: selenium
  before_script:
    - apt-get update && apt-get install -y curl
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest test.py
  only:
    - master
