image: python:3.9

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y wget unzip
  - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/
  - apt-get install -y chromium-browser

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Убедитесь, что в requirements.txt указаны все необходимые библиотеки, включая selenium и pytest
    - pytest -v  # Запуск тестов
