name: CI

on:
  schedule:
    - cron: '*/10 * * * *'  # Запускать каждые 10 мин
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что у вас есть requirements.txt

      - name: Run tests
        run: |
          python test.py  # Запустите ваш файл автотеста
